name: "Whisper_ASR_Training"
model:
  pad_id: 0
  blank_id: 1

  train_ds:
    manifest_filepath: "./data/train.json"
    sample_rate: 16000
    batch_size: 1
    shuffle: True
    num_workers: 4
    pin_memory: True

  validation_ds:
    manifest_filepath: "./data/val.json"
    sample_rate: 16000
    batch_size: 1
    shuffle: False
    num_workers: 4
    pin_memory: True

  test_ds:
    manifest_filepath: "./data/test.json"
    sample_rate: 16000
    batch_size: 1
    shuffle: False
    num_workers: 4
    pin_memory: True

optim:
  name: adamw
  lr: 0.001
  weight_decay: 0.01

trainer:
  accelerator: 'gpu'
  devices: 1
  max_epochs: 2
  gradient_clip_val: 0.5
  logger: True
  precision: 32  # Ensure 32-bit precision
  accumulate_grad_batches: 2
  deterministic: True
  enable_checkpointing: True
  strategy: 'auto'
  callbacks: []